on:
  push:
    branches:
      - dev

name: dev-workflow
jobs:
  version-update:
    runs-on: "ubuntu-20.04"
    name: version-update
    steps:
      
      # get git code
      - name: Check out source repository
        id: checkoutsourcerepo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GitPASSWORD }}
          
      # Generates the core version based on the core-version file
      - name: Generate core-versions
        uses: HardNorth/github-version-generate@v1.1.0
        with:
          version-source: file
          version-file: version.txt
          next-version-increment-patch: ${{ contains(env.VERSION_FRAGMENT, 'patch') }}
          next-version-increment-minor: ${{ contains(env.VERSION_FRAGMENT, 'minor') }}
          next-version-increment-major: ${{ contains(env.VERSION_FRAGMENT, 'major') }}

      - name: Update the version files
        run: |
          git config --global user.email "benedikt.liebs@fellow-consulting.de"
          git config --global user.name "FellowFellow"
          echo ${{ env.NEXT_VERSION }} > version.txt
          git add version.txt
          git tag ${{ env.NEXT_VERSION }} HEAD
          git commit -m "version update"
          git push
          git push --tags






